before_script:
        - g++-5 -v

build:
        script:
                - make -j10 CXX=g++-5
test:
        script:
                - make -j10 test CXX=g++-5
integration-test:
        script:
                -make -j10 CXX=g++-5
                -misc/scripts/integration-tests

