before_script:
        - g++-5 -v

test:
        script:
                - make -j10 test CXX=g++-5
integration-test:
        script:
                - make -j10 CXX=g++-5 PCW_DB_HOST=pocoweb
                - misc/scripts/integration-tests config.ini 2>/dev/null
                - cat config.ini

