before-script:
        - apt-get update && apt-get install -y -qq libboost-dev g++
        - g++ -v

build:
        -script:
                - make -j4

test:
        -script:
                - make test

