before_script:
        - g++-5 -v

unit-tests:
        script:
                - make -j10 test CXX=g++-5
integration-test:
        script:
                - wget http://cis.lmu.de/~finkf/pocoweb-env --output-document env
                - cat ./env
                - bash misc/config/config.sh ./env > config.ini
                - cat config.ini
                - misc/scripts/integration-tests config.ini

