before_script:
        - sudo apt-get install libleptonica-dev
        - g++-5 -v

build:
        script:
                - make -j4 CXX=g++-5

test:
        script:
                - make -j4 test CXX=g++-5

