version: '3'
services:
  # web server
  nginx:
    build: nginx/
    ports:
      - "80:80"
    volumes:
      - /home/flo/data/srv/pocoweb/www-data:/www-data:ro
      - /home/flo/data/srv/pocoweb/project-data:/project-data:ro
    links:
      - fpm
      - pocoweb
    depends_on:
      - fpm
      - pocoweb
      - pcwauth
    restart: always
  # php fast cgi
  fpm:
    image: php:fpm
    ports:
      - "9000:9000"
    volumes:
      - /home/flo/data/srv/pocoweb/www-data:/www-data:ro
      - /home/flo/data/srv/pocoweb/tmp-data:/tmp:rw
    restart: always

  # pocoweb rest service
  pocoweb:
    build: pocoweb/
    ports:
      - "8080:8080"
    links:
      - db
    volumes:
      - /home/flo/data/srv/pocoweb/project-data:/project-data:rw
      - /home/flo/data/srv/pocoweb/tmp-data:/tmp:rw
      - /home/flo/data/srv/pocoweb/www-data:/www-data:rw
      - /home/flo/data/srv/pocoweb/language-data:/language-data:ro
    depends_on:
      - db
    restart: always

  # mysql database
  db:
    image: mariadb
    ports:
      - "3306:3306"
    volumes:
      - /home/flo/data/srv/pocoweb/db-data:/var/lib/mysql
      - ./db:/etc/mysql/conf.d:ro
    restart: always
    env_file:
      - env.sh
    #command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci

  # pocoweb authentification and user management
  pcwauth:
    build: pcwauth/
    ports:
      - "8081:8081"
    links:
      - db
      - pocoweb
    depends_on:
      - db
    restart: always
    env_file:
      - env.sh
