version: '3'
services:
  # web server
  nginx:
    env_file:
      - env.sh
    build: nginx/
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${PCW_BASE_DIR}/www-data:/www-data:ro
      - ${PCW_BASE_DIR}/project-data:/project-data:ro
      - letsencrypt_certs:/etc/nginx/certs
      - letsencrypt_www:/var/www/letsencrypt
    links:
      - pocoweb
    depends_on:
      - pocoweb
      - pcwauth
    restart: always
  # let's encrypt for https
  letsencrypt:
    build: letsencrypt/
    command: /bin/true
    volumes:
      - letsencrypt_certs:/etc/letsencrypt
      - letsencrypt_www:/var/www/letsencrypt
  # pocoweb rest service
  pocoweb:
    image: flobar/pocoweb
    links:
      - db
    volumes:
      - ${PCW_BASE_DIR}/project-data:/project-data:rw
      - ${PCW_BASE_DIR}/tmp-data:/tmp:rw
      - ${PCW_BASE_DIR}/www-data:/www-data:rw
    depends_on:
      - db
    restart: always
    env_file:
      - env.sh

  # mysql database
  db:
    image: mariadb
    volumes:
      - ${PCW_BASE_DIR}/db-data:/var/lib/mysql
      - ./db:/etc/mysql/conf.d:ro
    restart: always
    env_file:
      - env.sh

  # pocoweb authentification
  pcwauth:
    # build: pcwauth/
    image: flobar/pcwauth
    links:
      - db
      - pocoweb
      - pcwprofiler
      - pcwusers
      - pcwpostcorrection
      - pcwocr
      - pcwpkg
    depends_on:
      - db
    restart: always
    env_file:
      - env.sh

  # pocoweb profiling
  pcwprofiler:
    image: flobar/pcwprofiler
    restart: always
    links:
      - db
    depends_on:
      - db
    env_file:
      - env.sh
    volumes:
      - ${PCW_BASE_DIR}/project-data:/project-data:rw

  # pocoweb user management
  pcwusers:
    image: flobar/pcwusers
    restart: always
    links:
      - db
    depends_on:
      - db
    env_file:
      - env.sh

  # pocoweb post-correction
  pcwpostcorrection:
    image: flobar/pcwpostcorrection
    restart: always
    links:
      - db
      - pocoweb
    depends_on:
      - db
    env_file:
      - env.sh
    volumes:
      - ${PCW_BASE_DIR}/project-data:/project-data:rw

  # pocoweb ocr
  pcwocr:
    image: flobar/pcwocr
    restart: always
    links:
      - db
    depends_on:
      - db
    env_file:
      - env.sh
    volumes:
      - ${PCW_BASE_DIR}/project-data:/project-data:rw
      - ${PCW_BASE_DIR}/ocr-data:/data/models:rw

  # pocoweb pkg
  pcwpkg:
    image: flobar/pcwpkg
    restart: always
    links:
      - db
    depends_on:
      - db
    env_file:
      - env.sh
# named volumes
volumes:
  letsencrypt_certs:
  letsencrypt_www:
